### ISSUE TITLE
Can't compile with make when initial clone

### ISSUE THREAD

**Issue by cos18** [Eleveres/simple_sockets#1]
When I clone repository and using make command, there's error like this.

```terminal
gcc -c -Wall -Wextra src/accept_connection.c src/connect_to_server.c src/create_ipv4_server.c src/create_ipv6_server.c src/recvall.c src/sendall.c src/print_bytearray.c src/encoding.c
mv accept_connection.o connect_to_server.o create_ipv4_server.o create_ipv6_server.o recvall.o sendall.o print_bytearray.o encoding.o  obj/
usage: mv [-f | -i | -n] [-v] source target
       mv [-f | -i | -n] [-v] source ... directory
make: *** [simple_socket.a] Error 64
```

I think there's no obj folder when clone.
You should add .gitkeep file in obj and commit or not using obj folder.
More details about gitkeep : https://stackoverflow.com/questions/7229885/what-are-the-differences-between-gitignore-and-gitkeep

**Comment by Eleveres** [comment]
Hi, you're totally right I completely forgot git doesn't push empty directories. I added the .gitkeep you should be good to go now if try cloning the repo again. Thanks!
