### ISSUE TITLE
Shift operator overflow at decode_64bit function

### ISSUE THREAD

**Issue by cos18** [Eleveres/simple_sockets#2]
I'm using your code at [my school project](https://github.com/cos18/linux-socket). Thanks for the wonderful code!

When I using your `decode_64bit` function, numbers get overflowed.
Default shift operator can hold 31bit numbers. When they try number over than that, they overflow. I fix code at my project by casting left-hand number to `uint64_t` like this.

```C
uint64_t decode_64bit(uint8_t *byetarray)
{
    uint64_t decoded = 0;
    uint8_t shift = 56;
    for (uint16_t i = 0; i < 8; i++)
    {
        decoded = decoded | (uint64_t)byetarray[i] << shift;
        shift -= 8;
    }
    return decoded;
}
```
More info : https://stackoverflow.com/questions/10499104/is-shifting-more-than-32-bits-of-a-uint64-t-integer-on-an-x86-machine-undefined

**Comment by Eleveres** [comment]
Damn, completely forgot about that! Thanks again for your help. I'm happy to hear that you're using this library for your work at school! I fixed the code everything should be fine now.
